server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nuovoProgetto
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql